---
base: &base
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: "<%= ENV['CLOUDINARY_API_KEY'] %>"
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
development:
  <<: *base
  enhance_image_tag: true
  static_image_support: false
production:
  <<: *base
  enhance_image_tag: true
  static_image_support: true
test:
  <<: *base
  enhance_image_tag: true
  static_image_support: false
